# Site settings
title: Jay Mishra | Web Developer, Technical Mentor & Digital Marketer 
email: akajaymishra@outlook.com
url: https://instagram.com/akajaymishra
description: "Namoh 🙏 and welcome to my website, it's your gateway to the digital world! As a seasoned professional in web development and digital marketing, I am committed to propelling your online presence to new heights. With expertise in the latest web technologies and a deep understanding of digital marketing strategies, I provide tailored solutions that drive growth and success. With me, your vision is transformed into a digital reality, creating websites that are not only visually appealing but also functionally robust. My data-driven digital marketing strategies are designed to increase visibility, engage users, and convert leads. Embark on a digital journey with me, and unlock the full potential of your business in the online world."
keywords: "web, web developer, website, website creator, web development, digital marketing, tailored solutions, data-driven digital marketing strategies, increase visibility, website builder, web design company, responsive web design, web development company, web design software, how to design a website, web application development, what is a website, what is a web portal, what is wordpress, what is web technology, what is connectivity, get your professional website in under 7000, get your beginner website in 2000, get your business website in 10000, wordpress development, wordpress plugin, wordpress plugin development, wordpress theme, wordpress theme development, wordpress, wordpress website, wordpress website development, mern developer, nodejs developer, react developer, mern software developer, software developer, node developer, website creation with nodejs and mern"
skills: "Web Developer - Digital Marketer - User Experience Designer"
meta_author: Mishra Jay

# Google webmaster tools 
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jay Mishra
  location: India
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/akajaymishra
  - title: facebook
    url: http://facebook.com/akajaymishra 
  - title: stack-overflow
    url: https://stackoverflow.com/users/23229658/akascientist
  - title: bitbucket
    url: https://bitbucket.org/official-akascientist
  - title: github
    url: http://github.com/akascientist

# Postal address (add as many lines as necessary)
address:
  - line: Noida Sec 59
  - line: Near Metro Station, UP- 201301

# Credits content
credits: 'Jay Mishra is a professional web developer and digital marketer working for businesses and clients trying to achieve a standard space online 😊 <a href="https://instagram.com/jaymishra"></a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
